const CardsData = [
    {
        id: 1,
        rname: "The Great Gatsby",
        imgdata: "https://m.media-amazon.com/images/I/41XMaCHkrgL.jpg",
        address: "F. Scott Fitzgerald",
        delimg: "https://m.media-amazon.com/images/I/81X6sA+X-BL._AC_UY218_.jpg",
        somedata: "A Jazz Age tale of love and obsession.",
        price: 350,
        rating: "4.4",
        arrimg: "https://m.media-amazon.com/images/I/81X6sA+X-BL._AC_UY218_.jpg",
        qnty: 0,
        genre: "Classic"
    },
    {
        id: 2,
        rname: "1984",
        imgdata: "https://m.media-amazon.com/images/I/91SZSW8qSsL._AC_UY218_.jpg",
        address: "George Orwell",
        delimg: "https://m.media-amazon.com/images/I/71kxa1-0mfL._AC_UY218_.jpg",
        somedata: "A dystopian novel of totalitarianism.",
        price: 400,
        rating: "4.7",
        arrimg: "https://m.media-amazon.com/images/I/71kxa1-0mfL._AC_UY218_.jpg",
        qnty: 0,
        genre: "Dystopian"
    },
    {
        id: 3,
        rname: "To Kill a Mockingbird",
        imgdata: "https://m.media-amazon.com/images/I/41j-s9fHJcL.jpg",
        address: "Harper Lee",
        delimg: "https://m.media-amazon.com/images/I/71FXfPSFNyL._AC_UY218_.jpg",
        somedata: "A novel on racial injustice.",
        price: 300,
        rating: "4.8",
        arrimg: "https://m.media-amazon.com/images/I/71FXfPSFNyL._AC_UY218_.jpg",
        qnty: 0,
        genre: "Classic"
    },
    {
        id: 4,
        rname: "Pride and Prejudice",
        imgdata: "https://rukminim2.flixcart.com/image/850/1000/xif0q/book/f/s/1/pride-prejudice-original-imagy32ephewfga2.jpeg?q=90&crop=false",
        address: "Jane Austen",
        delimg: "https://m.media-amazon.com/images/I/71YbYtKhdwL._AC_UY218_.jpg",
        somedata: "A romantic critique of 18th-century society.",
        price: 250,
        rating: "4.6",
        arrimg: "https://m.media-amazon.com/images/I/71YbYtKhdwL._AC_UY218_.jpg",
        qnty: 0,
        genre: "Romance"
    },
    {
        id: 5,
        rname: "The Catcher in the Rye",
        imgdata: "https://images-na.ssl-images-amazon.com/images/I/81OthjkJBuL.jpg",
        address: "J.D. Salinger",
        delimg: "https://m.media-amazon.com/images/I/81MeUpZ2tTL._AC_UY218_.jpg",
        somedata: "A story of teenage rebellion.",
        price: 370,
        rating: "4.3",
        arrimg: "https://m.media-amazon.com/images/I/81MeUpZ2tTL._AC_UY218_.jpg",
        qnty: 0,
        genre: "Coming-of-age"
    },
    {
        id: 6,
        rname: "The Hobbit",
        imgdata: "https://images-na.ssl-images-amazon.com/images/I/91b0C2YNSrL.jpg",
        address: "J.R.R. Tolkien",
        delimg: "https://m.media-amazon.com/images/I/91O4N1x4uQL._AC_UY218_.jpg",
        somedata: "A fantasy quest for treasure.",
        price: 450,
        rating: "4.8",
        arrimg: "https://m.media-amazon.com/images/I/91O4N1x4uQL._AC_UY218_.jpg",
        qnty: 0,
        genre: "Fantasy"
    },
    {
        id: 7,
        rname: "Moby Dick",
        imgdata: "https://m.media-amazon.com/images/I/71d5wo+-MuL._AC_UF1000,1000_QL80_.jpg",
        address: "Herman Melville",
        delimg: "https://m.media-amazon.com/images/I/81nZJd8-XpL._AC_UY218_.jpg",
        somedata: "A whaling voyage and revenge quest.",
        price: 420,
        rating: "4.1",
        arrimg: "https://m.media-amazon.com/images/I/81nZJd8-XpL._AC_UY218_.jpg",
        qnty: 0,
        genre: "Adventure"
    },
    {
        id: 8,
        rname: "War and Peace",
        imgdata: "https://m.media-amazon.com/images/I/91teiIZ5vwL._AC_UF1000,1000_QL80_.jpg",
        address: "Leo Tolstoy",
        delimg: "https://m.media-amazon.com/images/I/81O5zAdEL+L._AC_UY218_.jpg",
        somedata: "A tale of the Napoleonic Wars in Russia.",
        price: 500,
        rating: "4.7",
        arrimg: "https://m.media-amazon.com/images/I/81O5zAdEL+L._AC_UY218_.jpg",
        qnty: 0,
        genre: "Historical"
    },
    {
        id: 9,
        rname: "The Alchemist",
        imgdata: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1654371463i/18144590.jpg",
        address: "Paulo Coelho",
        delimg: "https://m.media-amazon.com/images/I/81hq4HWrHkL._AC_UY218_.jpg",
        somedata: "A shepherd's quest for treasure.",
        price: 300,
        rating: "4.6",
        arrimg: "https://m.media-amazon.com/images/I/81hq4HWrHkL._AC_UY218_.jpg",
        qnty: 0,
        genre: "Adventure"
    },
    {
        id: 10,
        rname: "Brave New World",
        imgdata: "https://m.media-amazon.com/images/I/81NQ4+SdRGL._AC_UF1000,1000_QL80_.jpg",
        address: "Aldous Huxley",
        delimg: "https://m.media-amazon.com/images/I/71Fd-tDUGHL._AC_UY218_.jpg",
        somedata: "A critique of technological advancement.",
        price: 340,
        rating: "4.5",
        arrimg: "https://m.media-amazon.com/images/I/71Fd-tDUGHL._AC_UY218_.jpg",
        qnty: 0,
        genre: "Dystopian"
    },
    {
        id: 11,
        rname: "The Road",
        imgdata: "https://m.media-amazon.com/images/I/51M7XGLQTBL._AC_UF1000,1000_QL80_.jpg",
        address: "Cormac McCarthy",
        delimg: "https://m.media-amazon.com/images/I/71U7WJgW7WL._AC_UY218_.jpg",
        somedata: "A post-apocalyptic journey of survival.",
        price: 390,
        rating: "4.7",
        arrimg: "https://m.media-amazon.com/images/I/71U7WJgW7WL._AC_UY218_.jpg",
        qnty: 0,
        genre: "Post-apocalyptic"
    },
    {
        id: 12,
        rname: "Gone with the Wind",
        imgdata: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQEGdrKNOg9EfH2PVd3zmm4wm_qWXHT-UBAcw&s",
        address: "Margaret Mitchell",
        delimg: "https://m.media-amazon.com/images/I/71ETjz6B2xL._AC_UY218_.jpg",
        somedata: "A Southern woman's epic struggle during the Civil War.",
        price: 550,
        rating: "4.6",
        arrimg: "https://m.media-amazon.com/images/I/71ETjz6B2xL._AC_UY218_.jpg",
        qnty: 0,
        genre: "Historical"
    },
    {
        id: 13,
        rname: "Catch-22",
        imgdata: "https://m.media-amazon.com/images/I/71Ym0vDDWsL._AC_UF1000,1000_QL80_.jpg",
        address: "Joseph Heller",
        delimg: "https://m.media-amazon.com/images/I/81m1u7xxoML._AC_UY218_.jpg",
        somedata: "A satirical novel about the absurdities of war.",
        price: 420,
        rating: "4.4",
        arrimg: "https://m.media-amazon.com/images/I/81m1u7xxoML._AC_UY218_.jpg",
        qnty: 0,
        genre: "Satire"
    },
    {
        id: 14,
        rname: "The Bell Jar",
        imgdata: "https://m.media-amazon.com/images/I/71+QjnynosL._AC_UF1000,1000_QL80_.jpg",
        address: "Sylvia Plath",
        delimg: "https://m.media-amazon.com/images/I/71by1rkDeBL._AC_UY218_.jpg",
        somedata: "A semi-autobiographical novel about mental illness.",
        price: 310,
        rating: "4.5",
        arrimg: "https://m.media-amazon.com/images/I/71by1rkDeBL._AC_UY218_.jpg",
        qnty: 0,
        genre: "Autobiography"
    },
    {
        id: 15,
        rname: "A Tale of Two Cities",
        imgdata: "https://m.media-amazon.com/images/I/71CQFGiPA+L._AC_UF1000,1000_QL80_.jpg",
        address: "Charles Dickens",
        delimg: "https://m.media-amazon.com/images/I/71hIGwm0UQL._AC_UY218_.jpg",
        somedata: "A historical novel set during the French Revolution.",
        price: 340,
        rating: "4.7",
        arrimg: "https://m.media-amazon.com/images/I/71hIGwm0UQL._AC_UY218_.jpg",
        qnty: 0,
        genre: "Historical"
    },
];

export default CardsData;
